version: '3.8'
services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - '9411:9411'

  user-service-db:
    image: mariadb:11.2.4
    networks:
      - plagiarismcheck_network
    environment:
      - MARIADB_DATABASE=user_service
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_USER=muhayu
      - MARIADB_PASSWORD=1234
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  zookeeper:
    image: 'zookeeper'
    networks:
      - plagiarismcheck_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  kafka:
    image: 'bitnami/kafka'
    networks:
      - plagiarismcheck_network
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=LC://kafka:29092,LX://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LC

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - plagiarismcheck_network
    ports:
      - '8989:8080'
    restart: always
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  user-api:
    image: user-api:1.0.0
    depends_on:
      - user-service-db
      - kafka
    networks:
      - plagiarismcheck_network
    ports:
      - '8080:8080'
    environment:
      - USE_PROFILE=local

networks:
  plagiarismcheck_network:
    driver: bridge

