spring:
  kafka:
    bootstrap-servers:
      - 10.0.200.52:9092
      - 10.0.200.53:9092
      - 10.0.200.54:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
