spring:
  cloud:
    openfeign:
      compression:
        request:
          enabled: false
          min-request-size: 2048
          mime-types: application/json
        response:
          enabled: false