spring:
  application:
    name: user-kafka

  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      max-poll-records: 1
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
        max.poll.interval.ms: 300000
        session.timeout.ms: 30000
        heartbeat-interval: 10000
      group-id: ${spring.application.name}-local
      isolation-level: read_committed
    producer:
      transaction-id-prefix: tx-
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    listener:
      concurrency: 3
      ack-mode: manual_immediate

management:
  tracing:
    sampling:
      probability: 1
    enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

kafka:
  producer:
    topic:
      user-created: queuing.copykiller.service-template.user-created
  consumer:
    topic:
      login-user: queuing.copykiller.service-template.user-login

